[package]
name = "sebastian"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
clap = { version = "3.2.17", features = ["derive"] }
directories = "4.0.1"
sebastian-core = { version = "0.1.0", path = "../lib" }
indicatif = "0.17.0"
inquire = "0.3.0"
lazy_static = "1.4.0"
regex = "1.6.0"
serde = { version = "1.0.144", features = ["derive"] }
toml = "0.5.9"
log = "0.4.17"
env_logger = "0.9.0"
